[package]
edition = "2021"
name = "supercluster"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"
geojson = "*"
rs-kdbush = "0.2.0"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
