/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface DefaultOptions {
  minZoom?: number
  maxZoom?: number
  minPoints?: number
  radius?: number
  extent?: number
  nodeSize?: number
  log?: boolean
  generateId?: boolean
}
export class SuperCluster {
  constructor(options?: DefaultOptions | undefined | null)
}
